feature_weights = {
    "syllabic": 1,
    "consonantal": 1,
    "approximant": 1,
    "sonorant": 1,
    "continuant": 1,
    "delayed release": 1,
    "tap": 1,
    "trill": 1,
    "nasal": 1,
    "lateral": 1,
    "voice": 1,
    "spread gl": 1,
    "constr gl": 1,
    "labial": 1,
    "round": 1,
    "labiodental": 1,
    "coronal": 1,
    "anterior": 1,
    "distributed": 1,
    "strident": 1,
    "dorsal": 1,
    "high": 1,
    "low": 1,
    "front": 1,
    "back": 1,
    "tense": 1,
}

features = {
    "P": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "-",
        "labiodental": "-",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "B": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "-",
        "labiodental": "-",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "M": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "-",
        "labiodental": "-",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "W": {
        "syllabic": "-",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "+",
        "labiodental": "-",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "-",
    },
    "F": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "-",
        "labiodental": "+",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "V": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "-",
        "labiodental": "+",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "TH": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "-",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "DH": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "+",
        "strident": "-",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "T": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "D": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "S": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "+",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "Z": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "+",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "N": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "R": {
        "syllabic": "-",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "L": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "+",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "+",
        "distributed": "-",
        "strident": "-",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "SH": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "ZH": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "CH": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "JH": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "+",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "Y": {
        "syllabic": "-",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "+",
        "anterior": "-",
        "distributed": "+",
        "strident": "-",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "-",
    },
    "K": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "-",
    },
    "G": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "-",
        "delayed release": "-",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "-",
    },
    "NG": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "+",
        "continuant": "-",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "+",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "-",
        "tense": "-",
    },
    "HH": {
        "syllabic": "-",
        "consonantal": "+",
        "approximant": "-",
        "sonorant": "-",
        "continuant": "+",
        "delayed release": "+",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "-",
        "spread gl": "+",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "-",
        "high": "0",
        "low": "0",
        "front": "0",
        "back": "0",
        "tense": "0",
    },
    "IY": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "+",
    },
    "IH": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "-",
    },
    "E": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "-",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "+",
    },
    "EH": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "-",
        "low": "-",
        "front": "+",
        "back": "-",
        "tense": "-",
    },
    "AE": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "-",
        "low": "+",
        "front": "+",
        "back": "-",
        "tense": "-",
    },
    "UW": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "+",
        "labiodental": "-",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+",
    },
    "UH": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "+",
        "labiodental": "-",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "+",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "-",
    },
    "O": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "+",
        "labiodental": "-",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "+",
    },
    "AH": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "-",
    },
    "AO": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "+",
        "round": "+",
        "labiodental": "-",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "-",
        "low": "-",
        "front": "-",
        "back": "+",
        "tense": "-",
    },
    "AA": {
        "syllabic": "+",
        "consonantal": "-",
        "approximant": "+",
        "sonorant": "+",
        "continuant": "+",
        "delayed release": "0",
        "tap": "-",
        "trill": "-",
        "nasal": "-",
        "lateral": "-",
        "voice": "+",
        "spread gl": "-",
        "constr gl": "-",
        "labial": "-",
        "round": "0",
        "labiodental": "0",
        "coronal": "-",
        "anterior": "0",
        "distributed": "0",
        "strident": "0",
        "dorsal": "+",
        "high": "-",
        "low": "+",
        "front": "-",
        "back": "+",
        "tense": "-",
    },
}
